[pytest]
addopts =
    -v
    -s
    --tb=short
    --alluredir=reports/allure-results
    --clean-alluredir

testpaths = tests

python_files = test_*.py

markers =
    smoke
    regression
    ui
    api
    slow